name: Run watcher
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: denolib/setup-deno@v2
      #   with:
      #     deno-version: v1.x
      # - run: |
      #     deno run --allow-net index.ts
